### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by ran66666** [LongDang2212/Rotate-Yolov5#1]
I am using your method to train the model. But I can't understand the meaning of  real and imagine.
![图片](https://user-images.githubusercontent.com/34015134/176180785-7fe4f724-689b-4514-802a-f8248930e3d9.png)

In [convert_habbof.py](https://github.com/LongDang2212/Rotate-Yolov5/blob/main/convert_habbof.py) line 27 and 28,the 5th and 6th could mean cos and sin.
Could you please explain the real and imagine for me ,thank you~

**Comment by LongDang2212** [comment]
Hi
![image](https://user-images.githubusercontent.com/57009019/176717814-3d075690-3885-457f-97fb-9c3921889bb7.png)
![image](https://user-images.githubusercontent.com/57009019/176718070-f33c162d-04b0-4061-a3f3-a8ec9c3bb64b.png)
cos mean real and imagine mean sin in my code.

**Comment by ran66666** [comment]
Thank you for your answer, this model work well on my dataset !
